name: Build Windows binaries

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  msys:
    runs-on: windows-2022
    strategy:
      matrix:
        mingw: ["MINGW32", "MINGW64"]
        include:
          - mingw: "MINGW32"
            package: "mingw-w64-i686"
          - mingw: "MINGW64"
            package: "mingw-w64-x86_64"
    defaults:
      run:
        shell: bash.exe --login -eo pipefail "{0}"
    env:
      MSYSTEM: ${{ matrix.mingw }}
      CHERE_INVOKING: 1
    name: MSYS2 ${{ matrix.mingw }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up shell
        run: echo "C:\msys64\usr\bin\" >> $GITHUB_PATH
        shell: pwsh
      - name: Print system version
        run: |
          uname
      - name: Install MinGW requirements
        run: |
          echo "$GITHUB_WORKSPACE"
          #pacman -S --noconfirm ${{ matrix.package }}-python3-setuptools
          # build the project
          #python3 setup.py install
      - name: Build binaries
        run: |
          make
          # add .exe extension to binaries
          mv alien-checksum-fixer/alien-checksum-fixer alien-checksum-fixer.exe
          mv castlevania-checksum-fixer/castlevania-checksum-fixer castlevania-checksum-fixer.exe
          mv cod-blackops-decrypter/cod-blackops-decrypter cod-blackops-decrypter.exe
          mv cod-checksum-fixer/cod-checksum-fixer cod-checksum-fixer.exe
          mv dbz-checksum-fixer/dbz-checksum-fixer dbz-checksum-fixer.exe
          mv deadspace-checksum-fixer/ds-checksum-fixer ds-checksum-fixer.exe
          mv diablo3-decrypter/diablo3-decrypter diablo3-decrypter.exe
          mv digimon-checksum-fixer/digimon-checksum-fixer digimon-checksum-fixer.exe
          mv dmc-decrypter/dmc-decrypter dmc-decrypter.exe
          mv ducktales-checksum-fixer/ducktales-checksum-fixer ducktales-checksum-fixer.exe
          mv dw8xl-decrypter/dw8xl-decrypter dw8xl-decrypter.exe
          mv ff13-decrypter/ff13-decrypter ff13-decrypter.exe
          mv ffxhd-checksum-fixer/ffxhd-checksum-fixer ffxhd-checksum-fixer.exe
          mv gta5-decrypter/gta5-decrypter gta5-save-decrypter.exe
          mv kh25-checksum-fixer/kh25remix-checksum-fixer kh25remix-checksum-fixer.exe
          mv lego-checksum-fixer/lego-checksum-fixer lego-checksum-fixer.exe
          mv mgs-hd-decrypter/mgs-hd-decrypter mgs-hd-decrypter.exe
          mv mgs-pw-decrypter/mgs-pw-decrypter mgs-pw-decrypter.exe
          mv mgs5-tpp-decrypter/mgs5-tpp-decrypter mgs5-tpp-decrypter.exe
          mv naughtydog-decrypter/naughtydog-decrypter naughtydog-save-decrypter.exe
          mv nfs-rivals-decrypter/nfsrivals-decrypter nfsrivals-decrypter.exe
          mv nfs-undercover-decrypter/nfs-undercover-decrypter nfs-undercover-decrypter.exe
          mv prototype-checksum-fixer/prototype-checksum-fixer prototype-checksum-fixer.exe
          mv ps4-borderlands3-decrypter/ps4-borderlands3-decrypter ps4-borderlands3-decrypter.exe
          mv ps4-rdr2-decrypter/rdr2-decrypter rdr2-decrypter.exe
          mv ps4-re-rev2-decrypter/re-revelations2-decrypter ps4-re-revelations2-decrypter.exe
          mv re-remaster-decrypter/re-remaster-decrypter re-remaster-decrypter.exe
          mv re-revelations2-decrypter/re-revelations2-decrypter re-revelations2-decrypter.exe
          mv silent-hill3-decrypter/silent-hill3-decrypter silent-hill3-decrypter.exe
          mv sw4-checksum-fixer/sw4-checksum-fixer sw4-checksum-fixer.exe
          mv tears2-checksum-fixer/tears2-checksum-fixer tears2-checksum-fixer.exe
          mv toz-checksum-fixer/toz-checksum-fixer toz-checksum-fixer.exe

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    
      - name: Compress output
        run: |
          tar -zcvf build.tar.gz \
            alien-checksum-fixer.exe \
            castlevania-checksum-fixer.exe \
            cod-blackops-decrypter.exe \
            cod-checksum-fixer.exe \
            dbz-checksum-fixer.exe \
            ds-checksum-fixer.exe \
            diablo3-decrypter.exe \
            digimon-checksum-fixer.exe \
            dmc-decrypter.exe \
            ducktales-checksum-fixer.exe \
            dw8xl-decrypter.exe \
            ff13-decrypter.exe \
            ffxhd-checksum-fixer.exe \
            gta5-save-decrypter.exe \
            kh25remix-checksum-fixer.exe \
            lego-checksum-fixer.exe \
            mgs-hd-decrypter.exe \
            mgs-pw-decrypter.exe \
            mgs5-tpp-decrypter.exe \
            naughtydog-save-decrypter.exe \
            nfsrivals-decrypter.exe \
            nfs-undercover-decrypter.exe \
            prototype-checksum-fixer.exe \
            ps4-borderlands3-decrypter.exe \
            rdr2-decrypter.exe \
            ps4-re-revelations2-decrypter.exe \
            re-remaster-decrypter.exe \
            re-revelations2-decrypter.exe \
            silent-hill3-decrypter.exe \
            sw4-checksum-fixer.exe \
            tears2-checksum-fixer.exe \
            toz-checksum-fixer.exe

      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ steps.slug.outputs.sha8 }}-${{matrix.mingw}}
          path: build.tar.gz
